### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by goxofy** [Dawnnnnnn/Cloud189#5]
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    fire.Fire()
  File "/home/tink/Cloud189/py-env/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/tink/Cloud189/py-env/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/tink/Cloud189/py-env/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 20, in login
    login.login(username, password)
  File "/home/tink/Cloud189/functions/login_function.py", line 66, in login
    redirect_url = response.json()['toUrl']
KeyError: 'toUrl'

**Comment by Dawnnnnnn** [comment]
我这里测试还正常，账号或密码里是否有特殊符号之类的呢

**Comment by goxofy** [comment]
没有符号，是大小写和数字

**Comment by Dawnnnnnn** [comment]
emmm，不好判断问题，能把你的账号密码用邮件发给我测试一下吗

**Comment by goxofy** [comment]
可以，您邮箱是多少

**Comment by Dawnnnnnn** [comment]
1050596704@qq.com

**Comment by goxofy** [comment]
已发

**Comment by Dawnnnnnn** [comment]
在看了，原因是账号登录的时候出了图形验证码，我想想怎么处理

**Comment by goxofy** [comment]
可以考虑保存到本地，让用户自行打开查看

**Comment by linker999** [comment]
顺便把自动登录做了吧 哈哈

**Comment by mengshouer** [comment]
或许是accountType的问题，我02改01就没验证码了
