### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by linker999** [Dawnnnnnn/Cloud189#6]
ash-4.3# cd /root/cloud189 && python3 main.py upload /volume1/musicfun/'Pacific Moon Records'
[2020-06-08 09:53:49] [upload_file:157] [/volume1/musicfun/Pacific Moon Records]是一个文件夹，开始解析目录结构 
[2020-06-08 09:53:49] [mkdir:68] 创建文件夹[Pacific Moon Records - Collection]成功，文件夹id为[6146419893988319]，父文件夹id为[-11] 
[2020-06-08 09:53:50] [mkdir:68] 创建文件夹[VA - Pacific Moon - 2007 - The Best Of Pacific Moon (FLAC)]成功，文件夹id为[5151019918418215]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:50] [mkdir:68] 创建文件夹[PMR-0022 兰ORCHID]成功，文件夹id为[6151119894166552]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:50] [mkdir:68] 创建文件夹[PMR-0056 侍Ⅱ SAMURAI COLLECTION]成功，文件夹id为[11446110329246496]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:50] [mkdir:68] 创建文件夹[PMR-0010 梦DREAM]成功，文件夹id为[11483110328229088]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:51] [mkdir:68] 创建文件夹[PMR-0018 雪SNOW]成功，文件夹id为[6142019891372594]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:51] [mkdir:68] 创建文件夹[PMR-0019-合輯-癒]成功，文件夹id为[11483110328229091]，父文件夹id为[6146419893988319] 
[2020-06-08 09:53:51] [mkdir:68] 创建文件夹[PMR-0032 夏SUMMER COLLECTION]成功，文件夹id为[6151119894166554]，父文件夹id为[6146419893988319] 
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    fire.Fire()
  File "/opt/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 31, in upload
    file_transport.upload_file(filepath, parent_folder_id)
  File "/root/cloud189/functions/file_transport_function.py", line 171, in upload_file
    folder_name, id, pid = self.operate.mkdir(folder_id, dir)
TypeError: cannot unpack non-iterable NoneType object

**Comment by linker999** [comment]
可能是子文件夹太多了 有84个。。

**Comment by linker999** [comment]
经测试，是这2个子文夹不行
PMR-0097 Kiyoshi Yoshida & 三塚幸彥 - 武士 Warriors
CHCA-1001-きゅらうた && 里アンナ（シングルCD）

**Comment by linker999** [comment]
经测试 应该是 & 不支持，另外现在也会有文件上传错位bug..
求开发者完善~~

**Comment by linker999** [comment]
应该是不支持& 字符，一般重试是几次呢
